# Generated by Django 4.0.5 on 2022-06-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=2048)),
                ('shorted_url', models.CharField(max_length=10)),
                ('detail_url', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.link')),
            ],
        ),
    ]
