# Generated by Django 4.0.5 on 2022-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='detail_url',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
