# Generated by Django 4.0.5 on 2022-06-19 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_detail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
