# Generated by Django 4.0.5 on 2022-06-25 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_click_click_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='click_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
