# Generated by Django 4.0.5 on 2022-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicked',
            name='click_date',
            field=models.DateTimeField(),
        ),
    ]
